/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AButton: typeof import('@arco-design/web-vue')['Button']
    ACard: typeof import('@arco-design/web-vue')['Card']
    ACol: typeof import('@arco-design/web-vue')['Col']
    AModal: typeof import('@arco-design/web-vue')['Modal']
    ARow: typeof import('@arco-design/web-vue')['Row']
    ASpace: typeof import('@arco-design/web-vue')['Space']
    ATable: typeof import('@arco-design/web-vue')['Table']
    ATableColumn: typeof import('@arco-design/web-vue')['TableColumn']
    ATag: typeof import('@arco-design/web-vue')['Tag']
    BrandIdentityFields: typeof import('./components/brand/BrandIdentityFields.vue')['default']
    BrandProfileFields: typeof import('./components/brand/BrandProfileFields.vue')['default']
    BrandSwitcher: typeof import('./components/BrandSwitcher.vue')['default']
    PageHeader: typeof import('./components/PageHeader.vue')['default']
    PreCollectionEmpty: typeof import('./components/PreCollectionEmpty.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SparkLine: typeof import('./components/SparkLine.vue')['default']
    ToastHost: typeof import('./components/ToastHost.vue')['default']
    UserMenu: typeof import('./components/UserMenu.vue')['default']
  }
}
