export type GlossaryTerm = {
  slug: string
  term: string
  short: string
  definition: string
  related?: string[]
}

/** 50+ GEO 术语实体，供 /glossary 批量索引 */
export const GEO_GLOSSARY_EXTENDED: GlossaryTerm[] = [
  {
    slug: 'geo',
    term: 'GEO',
    short: '生成式引擎优化',
    definition:
      'Generative Engine Optimization，关注品牌在生成式 AI 答案中的提及、排序、描述与引用，与传统 SEO 互补。',
    related: ['generative-engine-optimization', 'ai-visibility', 'seo'],
  },
  {
    slug: 'generative-engine-optimization',
    term: '生成式引擎优化',
    short: 'GEO 的中文全称',
    definition: '面向大模型/AI 搜索答案的品牌可见性与可引用性优化方法。',
    related: ['geo', 'llmo'],
  },
  {
    slug: 'ai-visibility',
    term: 'AI 搜索可见性',
    short: '品牌在 AI 答案中被看见的程度',
    definition: '通常用提及率、推荐位、引擎覆盖与问题覆盖等指标衡量。',
    related: ['mention-rate', 'recommendation-rank', 'engine-coverage'],
  },
  {
    slug: 'mention-rate',
    term: '品牌提及率',
    short: '问题采样中被提及的比例',
    definition: '在固定问题集与引擎下，品牌出现在答案中的次数占比。',
    related: ['ai-visibility', 'question-set'],
  },
  {
    slug: 'recommendation-rank',
    term: '平均推荐位',
    short: '被推荐时的平均排序',
    definition: '品牌在 AI 给出的推荐列表中的平均位置，数值越小越好。',
    related: ['ai-visibility', 'share-of-answer'],
  },
  {
    slug: 'citation-source',
    term: '引用源',
    short: 'AI 答案引用的信源',
    definition: '包括媒体、测评、问答、官网、白皮书等。类型分布能揭示缺口。',
    related: ['citation-gap', 'third-party-evidence'],
  },
  {
    slug: 'question-set',
    term: '问题集',
    short: '用于监测的固定提问列表',
    definition: 'GEO 监测的基准输入。问题集变更会使历史对比失效。',
    related: ['prompt-sampling', 'intent-coverage'],
  },
  {
    slug: 'brand-entity',
    term: '品牌实体',
    short: '品牌在知识层的统一表达',
    definition: '名称、别名、产品与事实字段的一致性，影响 AI 是否正确识别与描述。',
    related: ['entity-consistency', 'brand-alias'],
  },
  {
    slug: 'seo',
    term: 'SEO',
    short: '搜索引擎优化',
    definition: '优化网页在传统搜索结果页的排名与点击。与 GEO 互补：一个管蓝链，一个管 AI 答案。',
    related: ['geo', 'aio'],
  },
  {
    slug: 'aio',
    term: 'AIO',
    short: 'AI Overview / AI 答案优化相关说法',
    definition: '常指针对搜索引擎 AI 摘要或概览模块的优化讨论；与 GEO 概念有重叠，口径需按产品定义对齐。',
    related: ['geo', 'seo'],
  },
  {
    slug: 'llmo',
    term: 'LLMO',
    short: '大模型优化',
    definition: 'Large Language Model Optimization，强调面向大模型训练/检索内容的可引用性，常与 GEO 混用。',
    related: ['geo', 'generative-engine-optimization'],
  },
  {
    slug: 'share-of-answer',
    term: '答案份额',
    short: '品牌在答案推荐列表中的占位份额',
    definition: '衡量在多次采样中品牌进入推荐名单的相对份额，可与竞品对比。',
    related: ['mention-rate', 'competitor-gap'],
  },
  {
    slug: 'engine-coverage',
    term: '引擎覆盖',
    short: '被监测的 AI 引擎集合完整度',
    definition: '是否覆盖目标用户真实使用的生成式入口；名单应稳定以保持可比。',
    related: ['ai-visibility', 'prompt-sampling'],
  },
  {
    slug: 'intent-coverage',
    term: '问题覆盖率',
    short: '核心意图问题被覆盖的比例',
    definition: '品牌在目标问题集合中出现的覆盖广度，反映场景完整性。',
    related: ['question-set', 'mention-rate'],
  },
  {
    slug: 'description-sentiment',
    term: '描述倾向',
    short: 'AI 描述品牌时的情感与措辞',
    definition: '正面、中性、负面倾向及高频描述词，用于口碑与误述监测。',
    related: ['ai-sentiment', 'misattribution'],
  },
  {
    slug: 'ai-sentiment',
    term: 'AI 口碑',
    short: 'AI 答案中的品牌情感表现',
    definition: '从生成式回答中提取的品牌情感与风险表述，不等于社交媒体舆情全量。',
    related: ['description-sentiment', 'brand-entity'],
  },
  {
    slug: 'citation-gap',
    term: '引用缺口',
    short: '相对竞品缺少的可引用信源类型',
    definition: '在同类问题下，竞品被引用而你方缺失的信源类型或平台，是内容优先级的输入。',
    related: ['citation-source', 'content-brief'],
  },
  {
    slug: 'third-party-evidence',
    term: '第三方证据',
    short: '非官网的可验证背书',
    definition: '测评、媒体、分析师、客户白皮书等。AI 在高价值问题上常更偏好此类信源。',
    related: ['citation-source', 'citation-gap'],
  },
  {
    slug: 'content-brief',
    term: 'GEO 内容 Brief',
    short: '面向可引用写作的任务单',
    definition: '包含目标问题、必填事实、证据类型、段落结构与复测窗口。',
    related: ['citation-gap', 'extractable-content'],
  },
  {
    slug: 'extractable-content',
    term: '可抽取内容',
    short: '便于模型抽取结论与事实的结构',
    definition: '答案前置、列表/表格事实、明确日期与指标，降低被忽略或误读概率。',
    related: ['content-brief', 'answer-first'],
  },
  {
    slug: 'answer-first',
    term: '答案前置',
    short: 'H2 下首段直接给结论',
    definition: '面向 AI 与用户扫读的写作协议：先结论后展开，利于被引用。',
    related: ['extractable-content', 'faq-schema'],
  },
  {
    slug: 'faq-schema',
    term: 'FAQ / FAQPage',
    short: '问答结构与结构化数据',
    definition: '用真实问句组织 FAQ，并可用 FAQPage 等 schema 辅助理解（需与正文一致）。',
    related: ['answer-first', 'json-ld'],
  },
  {
    slug: 'json-ld',
    term: 'JSON-LD',
    short: '页面结构化数据嵌入格式',
    definition: '在页面中声明实体、文章、FAQ 等，帮助搜索与部分 AI 系统理解页面主题。',
    related: ['faq-schema', 'brand-entity'],
  },
  {
    slug: 'prompt-sampling',
    term: '问题采样',
    short: '按问题集向引擎发起只读查询',
    definition: 'GEO 监测的核心动作：固定提示、引擎、地域与时间，记录回答与引用。',
    related: ['question-set', 'sampling-window'],
  },
  {
    slug: 'sampling-window',
    term: '采样周期',
    short: '两次可比采样之间的时间窗口',
    definition: '常用周或双周。周期过短噪声大，过长则反应慢。',
    related: ['prompt-sampling', 'baseline'],
  },
  {
    slug: 'baseline',
    term: '可见性基线',
    short: '优化前的指标参照',
    definition: '用固定问题集得到的首期或对照期指标，用于判断后续是否改善。',
    related: ['mention-rate', 'geo-diagnosis'],
  },
  {
    slug: 'geo-diagnosis',
    term: 'GEO 诊断',
    short: '单次或轻量的可见性体检',
    definition: '只读采样输出健康度与行动优先级，适合建基线；持续监测需另开任务。',
    related: ['baseline', 'action-priority'],
  },
  {
    slug: 'action-priority',
    term: '行动优先级',
    short: 'P0/P1 内容与实体修复顺序',
    definition: '按影响×难度排序：先补高价值问题的证据缺口与误述。',
    related: ['citation-gap', 'geo-diagnosis'],
  },
  {
    slug: 'competitor-gap',
    term: '竞品差距',
    short: '同题下相对竞品的占位差',
    definition: '在同一问题集比较提及率、推荐位与引用结构，避免只看自身进步。',
    related: ['share-of-answer', 'ai-visibility'],
  },
  {
    slug: 'brand-alias',
    term: '品牌别名',
    short: '简称、英文名、旧名等变体',
    definition: '用户与 AI 常用别名提问；别名缺失会导致提及率被低估或实体分裂。',
    related: ['brand-entity', 'entity-consistency'],
  },
  {
    slug: 'entity-consistency',
    term: '实体一致性',
    short: '全站与外站品牌表达一致',
    definition: '名称、品类、产品事实在官网、百科、媒体中不互相矛盾。',
    related: ['brand-entity', 'brand-alias'],
  },
  {
    slug: 'misattribution',
    term: '误述 / 错归',
    short: 'AI 把错误事实安到品牌上',
    definition: '包括张冠李戴的功能、过时价格、错误归属的舆情等，需用事实页纠偏。',
    related: ['ai-sentiment', 'brand-entity'],
  },
  {
    slug: 'source-library',
    term: '信源库',
    short: '可发布与追踪的信源资产清单',
    definition: '媒体、社区、测评平台等目标信源及其状态，支撑发稿与引用回流。',
    related: ['citation-source', 'publish-track'],
  },
  {
    slug: 'publish-track',
    term: '发稿追踪',
    short: '记录发布并验证是否进入引用',
    definition: '把 URL、平台、时间与目标问题关联，复测时看是否出现在引用列表。',
    related: ['source-library', 'citation-gap'],
  },
  {
    slug: 'geo-agent',
    term: 'GEO Agent',
    short: '面向可引用写作与分析的助手',
    definition: '基于品牌档案与监测证据生成结构、brief 与草稿，发布前需人工核验事实。',
    related: ['content-brief', 'extractable-content'],
  },
  {
    slug: 'same-as',
    term: 'sameAs',
    short: '实体在其它权威站点的等同链接',
    definition: 'Organization schema 中的社交/百科等 URL，帮助消歧品牌实体。',
    related: ['brand-entity', 'json-ld'],
  },
  {
    slug: 'indexnow',
    term: 'IndexNow',
    short: '向搜索引擎即时提交 URL 变更',
    definition: 'Bing 等支持的协议，发布或更新页面后主动通知收录，缩短发现延迟。',
    related: ['sitemap-index', 'geo'],
  },
  {
    slug: 'sitemap-index',
    term: 'Sitemap Index',
    short: '分栏目的站点地图索引',
    definition: '将产品、学习、报告等拆成子 sitemap，便于增量提交与排查。',
    related: ['indexnow', 'llms-txt'],
  },
  {
    slug: 'llms-txt',
    term: 'llms.txt',
    short: '面向 AI 系统的站点说明文件',
    definition: '用纯文本列出站点主题与权威 URL，便于大模型优先引用正确页面。',
    related: ['geo', 'answer-first'],
  },
  {
    slug: 'noindex-personalized',
    term: '个性化结果 noindex',
    short: '对不可复用的个人报告限制索引',
    definition: '可分享诊断链接若含个性化数据，宜 noindex，避免薄内容进入索引。',
    related: ['geo-diagnosis', 'baseline'],
  },
  {
    slug: 'read-only-crawl',
    term: '只读采样',
    short: '不修改客户站点的抓取与提问',
    definition: '公开诊断与监测仅读取公开信息与引擎回答，不改代码、不发内容。',
    related: ['geo-diagnosis', 'prompt-sampling'],
  },
  {
    slug: 'evidence-pack',
    term: '证据包',
    short: '原始回答与引用归档',
    definition: '用于审计与汇报的原始采样材料，防止只展示加工后的分数。',
    related: ['prompt-sampling', 'baseline'],
  },
  {
    slug: 'category-benchmark',
    term: '品类基准',
    short: '同品类可见性参照',
    definition: '在同一问题集下的品类分布参照，禁止跨品类直接比提及率。',
    related: ['competitor-gap', 'ai-visibility'],
  },
  {
    slug: 'engine-variance',
    term: '引擎方差',
    short: '不同引擎表现差异程度',
    definition: '方差大时优先修复「某引擎未出现」，而不是只追综合分。',
    related: ['engine-coverage', 'ai-visibility'],
  },
  {
    slug: 'high-intent-query',
    term: '高意图问题',
    short: '接近购买/选型的提问',
    definition: '如「怎么选」「对比」「适合谁」，对转化影响通常高于泛认知题。',
    related: ['question-set', 'intent-coverage'],
  },
  {
    slug: 'long-tail-scene',
    term: '场景长尾',
    short: '细分场景与行业修饰问题',
    definition: '如「制造业」「跨境」等修饰，常是竞品差异化占位机会。',
    related: ['high-intent-query', 'intent-coverage'],
  },
  {
    slug: 'desensitized-report',
    term: '脱敏报告',
    short: '可公开分享的诊断摘要',
    definition: '去除客户敏感细节后回流流量站的报告页，用于案例与方法展示。',
    related: ['geo-diagnosis', 'evidence-pack'],
  },
  {
    slug: 'console-handoff',
    term: '控制台交接',
    short: '流量站到工作台的登录回跳',
    definition: '通过 consoleUrl + path + UTM/intent 完成账号侧履约，不在流量站自建账号体系。',
    related: ['geo-diagnosis', 'geo'],
  },
  {
    slug: 'utm-attribution',
    term: 'UTM 归因',
    short: '标记从流量站进入控制台的来源',
    definition: '如 utm_source=geo_hub，用于区分获客入口与转化路径。',
    related: ['console-handoff', 'geo'],
  },
  {
    slug: 'multi-brand-workspace',
    term: '多品牌工作区',
    short: '同一账号下管理多个品牌项目',
    definition: '每个品牌独立问题集、竞品与报告，指标口径保持一致以便横比。',
    related: ['question-set', 'brand-entity'],
  },
  {
    slug: 'retrieval-augmented',
    term: '检索增强回答',
    short: '模型结合检索结果生成答案',
    definition: '许多 AI 搜索会引用网页片段；可索引、可抽取的公开页更易进入引用池。',
    related: ['citation-source', 'extractable-content'],
  },
  {
    slug: 'grounding',
    term: '答案锚定 / Grounding',
    short: '回答依赖可追溯依据',
    definition: '有 grounding 的系统更依赖可验证信源；品牌需提供清晰事实与第三方背书。',
    related: ['retrieval-augmented', 'third-party-evidence'],
  },
  {
    slug: 'knowledge-freshness',
    term: '知识新鲜度',
    short: '公开事实是否足够新',
    definition: '过时价格、停产信息、旧案例会导致误述；重要事实应标注日期并更新。',
    related: ['misattribution', 'brand-entity'],
  },
  {
    slug: 'bing-chatgpt-retrieval',
    term: 'Bing / ChatGPT 检索关系',
    short: '收录与部分 AI 检索的关联',
    definition: 'Bing 收录与 IndexNow 对部分 ChatGPT 检索场景有利，故流量站需重视 Bing。',
    related: ['indexnow', 'sitemap-index'],
  },
]

export function getGlossaryExtended(slug: string) {
  return GEO_GLOSSARY_EXTENDED.find((t) => t.slug === slug)
}
