#!/usr/bin/env node
/**
 * 按环境写出各应用 .env（读 config/environments.json）
 * 用法：node scripts/apply-env.mjs local|test|prod
 */
import fs from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..')
const ENV = process.argv[2] || 'local'
const cfgPath = path.join(ROOT, 'config/environments.json')
const all = JSON.parse(fs.readFileSync(cfgPath, 'utf8'))
const e = all[ENV]
if (!e) {
  console.error(`未知环境: ${ENV}（可用: local | test | prod）`)
  process.exit(1)
}

function write(rel, body) {
  const file = path.join(ROOT, rel)
  fs.mkdirSync(path.dirname(file), { recursive: true })
  fs.writeFileSync(file, body.trimStart().replace(/\n+$/, '') + '\n', 'utf8')
  console.log('  ✓', rel)
}

const api = e.viteApiBase
const article = e.viteApiBase
const site = e.siteWeb

write(
  'apps/geo-user-dash-v2/.env.development',
  `
# AUTO-GENERATED by pnpm env:${ENV} — 勿手改；改 config/environments.json 后重新 apply
# 环境: ${e.label} (${ENV})
VITE_API_BASE=${api}
VITE_ARTICLE_BASE=${article}
VITE_SITE_URL=${site}
`,
)

write(
  'apps/geo-user-dash-v2/.env',
  `
# AUTO-GENERATED by pnpm env:${ENV} — build / docker 用
VITE_API_BASE=${api || e.geoApi}
VITE_ARTICLE_BASE=${article || e.geoApi}
VITE_SITE_URL=${site}
`,
)

write(
  'apps/geo-user-dash/.env.development',
  `
# AUTO-GENERATED by pnpm env:${ENV}
VITE_USE_MOCK=false
VITE_API_BASE=${api}
VITE_ARTICLE_BASE=${article}
VITE_SITE_URL=${site}
`,
)

write(
  'apps/geo-user-dash/.env',
  `
# AUTO-GENERATED by pnpm env:${ENV}
DASH_PORT=6002
VITE_USE_MOCK=false
VITE_API_BASE=${api || e.geoApi}
VITE_ARTICLE_BASE=${article || e.geoApi}
VITE_SITE_URL=${site}
`,
)

write(
  'apps/geo-admin/.env',
  `
# AUTO-GENERATED by pnpm env:${ENV}
VITE_API_BASE=${api}
`,
)

write(
  'apps/geo-admin/.env.development',
  `
# AUTO-GENERATED by pnpm env:${ENV}
VITE_API_BASE=${api}
`,
)

// geo-api：保留本地密钥，只合并公开 URL / 端口 / MONGO
const apiEnvPath = path.join(ROOT, 'apps/geo-api/.env')
const apiSnippet = `
# --- urls from pnpm env:${ENV} (${e.label}) ---
PUBLIC_API_URL=${e.publicApiUrl}
API_PORT=${e.apiPort}
MONGO_URL=${e.mongoUrl}
`.trim() + '\n'

if (fs.existsSync(apiEnvPath)) {
  let cur = fs.readFileSync(apiEnvPath, 'utf8')
  for (const key of ['PUBLIC_API_URL', 'API_PORT', 'MONGO_URL']) {
    const re = new RegExp(`^${key}=.*$`, 'm')
    const line = apiSnippet.split('\n').find((l) => l.startsWith(key + '='))
    if (!line) continue
    if (re.test(cur)) cur = cur.replace(re, line)
    else cur += (cur.endsWith('\n') ? '' : '\n') + line + '\n'
  }
  fs.writeFileSync(apiEnvPath, cur, 'utf8')
  console.log('  ✓ apps/geo-api/.env (merged PUBLIC_API_URL / API_PORT / MONGO_URL)')
} else {
  write(
    'apps/geo-api/.env',
    `
# AUTO-GENERATED by pnpm env:${ENV} — 密钥请自行追加
PUBLIC_API_URL=${e.publicApiUrl}
API_PORT=${e.apiPort}
MONGO_URL=${e.mongoUrl}
JWT_SECRET=change-me
COLLECTOR_API_KEY=change-me-collector-key
LLM_PROVIDER=deepseek
`,
  )
}

write(
  'apps/geo-user-site/.env',
  `
# AUTO-GENERATED — 官网已废弃；用户网页请用 apps/site-web
SITE_PORT=6003
NUXT_PUBLIC_API_BASE=/geo-api
NUXT_GEO_API_TARGET=${e.geoApi}
NUXT_PUBLIC_CONSOLE_URL=${e.geoDash}
`,
)

write(
  'apps/geo-test/.env',
  `
# AUTO-GENERATED by pnpm env:${ENV}
DASH_URL=${e.geoDash}
SITE_URL=${e.siteWeb}
API_URL=${e.geoApi}
ADMIN_URL=${e.geoAdmin}
`,
)

// —— site-manage 迁入：site-web / site-admin / site-server ——
write(
  'apps/site-web/.env',
  `
# AUTO-GENERATED by pnpm env:${ENV} — 勿手改；改 config/environments.json 后重新 apply
# 环境: ${e.label} (${ENV})
NUXT_API_BASE=${e.siteCms}
NUXT_PUBLIC_API_BASE=${e.siteCms}
NUXT_PUBLIC_SITE_URL=${e.siteWeb}
NUXT_PUBLIC_CONSOLE_URL=${e.geoDash}
NUXT_PUBLIC_GEO_API_BASE=/geo-api
NUXT_GEO_API_TARGET=${e.geoApi}
`,
)

write(
  'apps/site-admin/.env',
  `
# AUTO-GENERATED by pnpm env:${ENV}
VITE_API_PROXY_TARGET=${e.siteCms}
`,
)

write(
  'apps/site-server/.env',
  `
# AUTO-GENERATED by pnpm env:${ENV}
MONGODB_URL=${e.siteMongoUrl || 'mongodb://127.0.0.1:27017/site_manage'}
`,
)

fs.writeFileSync(path.join(ROOT, 'config/.current-env'), ENV + '\n', 'utf8')

console.log(`\n✅ 已切换到【${e.label}】环境 (${ENV})`)
console.log(`   业务API=${e.geoApi}`)
console.log(`   用户后台=${e.geoDash}${e.geoDashLegacy ? `（旧域 ${e.geoDashLegacy} 应 301）` : ''}`)
console.log(`   官网=${e.siteWeb}`)
console.log(`   CMS API=${e.siteCms}`)
console.log(`   之后: pnpm dev:all / pnpm dev:site`)
